services:
  
  db:
    image: postgres:18
    container_name: tasq-db
    environment:
      POSTGRES_USER: tasquser
      POSTGRES_PASSWORD: tasq#postgres
      POSTGRES_DB: tasq
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
